# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 00:44
from __future__ import unicode_literals

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование категории')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Категория подтверждена')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Содержимое комментария')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='List_of_tags_of_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ResultScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Наименование шкалы')),
                ('scale_divisions_amount', models.IntegerField(default=0, verbose_name='Количество делений оценочной шкалы')),
                ('divisions_layout', models.CharField(max_length=20, verbose_name='Разметка делений шкалы')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Наименование тега')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование теста')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(default='Описание теста отсутствует...', verbose_name='Описание теста')),
                ('controlling', models.BooleanField(default=False, verbose_name='Использование контроля прохождения теста')),
                ('time_restricting', models.BooleanField(default=False, verbose_name='Ограничение времени прохождения теста')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг теста')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_of_category', to='octapp.Category')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_with_scale', to='octapp.ResultScale')),
            ],
        ),
        migrations.AddField(
            model_name='list_of_tags_of_test',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists_with_tag', to='octapp.Tag'),
        ),
        migrations.AddField(
            model_name='list_of_tags_of_test',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_of_test', to='octapp.Test'),
        ),
        migrations.AddField(
            model_name='comment',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='octapp.Test'),
        ),
    ]
