# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 01:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='list_of_tags_of_test',
            options={'verbose_name': 'Список тегов теста', 'verbose_name_plural': 'Списки тегов теста'},
        ),
        migrations.AlterModelOptions(
            name='resultscale',
            options={'verbose_name': 'Оценочная шкала', 'verbose_name_plural': 'Оценочные шкалы'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
    ]
