# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0002_auto_20170417_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list_of_tags_of_test',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='list_of_tags_of_test',
            name='test',
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddField(
            model_name='tag',
            name='test',
            field=models.ManyToManyField(related_name='tags', to='octapp.Test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='test',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.DeleteModel(
            name='List_of_tags_of_test',
        ),
    ]
