# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0003_auto_20170417_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='octapp.Category'),
        ),
        migrations.AlterField(
            model_name='test',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='octapp.ResultScale'),
        ),
    ]
