# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0003_test_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultscale',
            name='divisions_layout',
            field=models.CharField(help_text="например, для 2-бальной шкалы (зачтено, незачтено) разметка делений может быть <q>'40,60'</q>", max_length=80, verbose_name='Разметка делений шкалы -- процентные доли каждого деления через запятую'),
        ),
    ]
