# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0003_auto_20170425_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultscale',
            name='divisions_layout',
            field=models.CharField(help_text='Следует указать [количество возможных баллов/оценок - 1] элементов. Например, для 2-бальной шкалы (зачтено, незачтено) разметка делений может быть <q>50</q>', max_length=80, verbose_name='Разметка делений шкалы -- процентные доли каждого деления через запятую'),
        ),
    ]
