# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0005_auto_20170417_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultscale',
            name='divisions_layout',
            field=models.CharField(max_length=20, verbose_name='Разметка делений шкалы -- процентные доли каждого деления через запятую'),
        ),
    ]
