# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 19:03
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0007_auto_20170503_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedQuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(default='', help_text='Используйте сервисы хранения изображений, если требуется добавить картинку.', verbose_name='Содержимое (наполнение, контент) варианта ответа')),
                ('option_number', models.IntegerField(verbose_name='Порядковый номер варианта ответа')),
            ],
            options={
                'verbose_name_plural': 'Элементы строки сопоставления',
                'ordering': ['question'],
                'verbose_name': 'Элемент строки сопоставления',
            },
        ),
        migrations.CreateModel(
            name='ComparisonQuestionElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_content', ckeditor.fields.RichTextField(default='', help_text='Используйте сервисы хранения изображений, если требуется добавить картинку.', verbose_name='Содержимое (наполнение, контент) элемента сопоставления')),
                ('element_index_number', models.IntegerField(verbose_name='Порядковый номер элемента сопоставления')),
            ],
            options={
                'verbose_name_plural': 'Элементы левого или правого ряда в вопросе на сопоставление',
                'ordering': ['question'],
                'verbose_name': 'Элемент левого или правого ряда в вопросе на сопоставление',
            },
        ),
        migrations.RenameField(
            model_name='sequencequestionelement',
            old_name='sequence_question',
            new_name='question',
        ),
        migrations.AddField(
            model_name='sequencequestionelement',
            name='element_content',
            field=ckeditor.fields.RichTextField(default='', help_text='Используйте сервисы хранения изображений, если требуется добавить картинку.', verbose_name='Содержимое (наполнение, контент) элемента последовательности'),
        ),
        migrations.AlterField(
            model_name='closedquestion',
            name='question_content',
            field=ckeditor.fields.RichTextField(default='', help_text='Используйте сервисы хранения изображений, если требуется добавить картинку.', verbose_name='Содержимое (наполнение, контент) вопроса.'),
        ),
        migrations.AlterField(
            model_name='comparisonquestion',
            name='question_content',
            field=ckeditor.fields.RichTextField(default='', help_text='Используйте сервисы хранения изображений, если требуется добавить картинку.', verbose_name='Содержимое (наполнение, контент) вопроса'),
        ),
        migrations.AlterField(
            model_name='openquestion',
            name='question_content_after_blank',
            field=ckeditor.fields.RichTextField(default='', help_text='Используйте сервисы хранения изображений, если требуется добавить картинку.', verbose_name='Содержимое (наполнение, контент) вопроса после пропуска (может отсутствовать)'),
        ),
        migrations.AlterField(
            model_name='openquestion',
            name='question_content_before_blank',
            field=ckeditor.fields.RichTextField(default='', help_text='Используйте сервисы хранения изображений, если требуется добавить картинку.', verbose_name='Содержимое (наполнение, контент) вопроса перед пропуском'),
        ),
        migrations.AlterField(
            model_name='sequencequestion',
            name='question_content',
            field=ckeditor.fields.RichTextField(default='', help_text='Используйте сервисы хранения изображений, если требуется добавить картинку.', verbose_name='Содержимое (наполнение, контент) вопроса'),
        ),
        migrations.AddField(
            model_name='comparisonquestionelement',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_elements', to='octapp.ComparisonQuestion', verbose_name='Вопрос на сопоставление, к которому относится элемент'),
        ),
        migrations.AddField(
            model_name='closedquestionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_question_options', to='octapp.ClosedQuestion', verbose_name='Вопрос закрытого типа, которому принадлежит данный вариант ответа'),
        ),
        migrations.AddField(
            model_name='comparisonquestion',
            name='left_row_elements',
            field=models.ManyToManyField(related_name='left_comparison_elements', to='octapp.ComparisonQuestionElement', verbose_name='Левые элементы сопоставления'),
        ),
        migrations.AddField(
            model_name='comparisonquestion',
            name='right_row_elements',
            field=models.ManyToManyField(related_name='right_comparison_elements', to='octapp.ComparisonQuestionElement', verbose_name='Правые элементы сопоставления'),
        ),
    ]
