# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 10:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0007_auto_20170418_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь-автор комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='octapp.Test', verbose_name='Тест, к которому относится комментарий'),
        ),
        migrations.AlterField(
            model_name='test',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, загрузивший тест'),
        ),
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='octapp.Category', verbose_name='Категория теста'),
        ),
        migrations.AlterField(
            model_name='test',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='octapp.ResultScale', verbose_name='Оценочная шкала теста'),
        ),
        migrations.AlterField(
            model_name='test',
            name='tag',
            field=models.ManyToManyField(to='octapp.Tag', verbose_name='Тег или теги теста'),
        ),
    ]
