# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0008_auto_20170418_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultscale',
            name='divisions_layout',
            field=models.CharField(help_text="например, для 2-бальной шкалы (зачтено, незачтено) разметка делений может быть <q>'40,60'</q>", max_length=20, verbose_name='Разметка делений шкалы -- процентные доли каждого деления через запятую'),
        ),
        migrations.AlterField(
            model_name='test',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='test',
            name='published_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='test',
            name='rating',
            field=models.IntegerField(default=0, editable=False, verbose_name='Рейтинг теста'),
        ),
    ]
