# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0009_auto_20170418_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='scale',
            new_name='result_scale',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='tag',
            new_name='tags',
        ),
    ]
