# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0009_auto_20170503_2157'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test_rate',
            new_name='TestRate',
        ),
        migrations.AlterField(
            model_name='questionoftest',
            name='type_of_question',
            field=models.CharField(choices=[('ClsdQ', 'закрытый'), ('OpndQ', 'открытый'), ('SqncQ', 'последовательность'), ('CmprsnQ', 'сопоставление')], max_length=7, unique=True, verbose_name='Тип теста, чтобы знать, к какому типу вопроса обращаться через связь'),
        ),
    ]
