# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0010_auto_20170503_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonquestion',
            name='left_row_elements',
            field=models.ManyToManyField(blank=True, related_name='left_comparison_elements', to='octapp.ComparisonQuestionElement', verbose_name='Левые элементы сопоставления'),
        ),
        migrations.AlterField(
            model_name='comparisonquestion',
            name='right_row_elements',
            field=models.ManyToManyField(blank=True, related_name='right_comparison_elements', to='octapp.ComparisonQuestionElement', verbose_name='Правые элементы сопоставления'),
        ),
    ]
