# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0010_auto_20170418_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': (('confirm_category', 'Can confirm_category'),), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
