# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 18:22
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0011_auto_20170504_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedquestion',
            name='question_content',
            field=ckeditor.fields.RichTextField(default='', help_text='Используйте сервисы хранения изображений, если требуется добавить картинку.', verbose_name='Содержимое (контент) вопроса.'),
        ),
        migrations.AlterField(
            model_name='closedquestionoption',
            name='content',
            field=ckeditor.fields.RichTextField(default='', help_text='Используйте сервисы хранения изображений, если требуется добавить картинку.', verbose_name='Содержимое (контент) варианта ответа'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Используйте сервисы хранения изображений, если требуется добавить картинку.', verbose_name='Содержимое (контент) комментария'),
        ),
        migrations.AlterField(
            model_name='comparisonquestion',
            name='question_content',
            field=ckeditor.fields.RichTextField(default='', help_text='Используйте сервисы хранения изображений, если требуется добавить картинку.', verbose_name='Содержимое (контент) вопроса'),
        ),
        migrations.AlterField(
            model_name='comparisonquestionelement',
            name='element_content',
            field=ckeditor.fields.RichTextField(default='', help_text='Используйте сервисы хранения изображений, если требуется добавить картинку.', verbose_name='Содержимое (контент) элемента сопоставления'),
        ),
        migrations.AlterField(
            model_name='openquestion',
            name='question_content_after_blank',
            field=ckeditor.fields.RichTextField(default='', help_text='Используйте сервисы хранения изображений, если требуется добавить картинку.', verbose_name='Содержимое (контент) после пропуска (может отсутствовать)'),
        ),
        migrations.AlterField(
            model_name='openquestion',
            name='question_content_before_blank',
            field=ckeditor.fields.RichTextField(default='', help_text='Используйте сервисы хранения изображений, если требуется добавить картинку.', verbose_name='Содержимое (контент) перед пропуском'),
        ),
        migrations.AlterField(
            model_name='sequencequestion',
            name='question_content',
            field=ckeditor.fields.RichTextField(default='', help_text='Используйте сервисы хранения изображений, если требуется добавить картинку.', verbose_name='Содержимое (контент) вопроса'),
        ),
        migrations.AlterField(
            model_name='sequencequestionelement',
            name='element_content',
            field=ckeditor.fields.RichTextField(default='', help_text='Используйте сервисы хранения изображений, если требуется добавить картинку.', verbose_name='Содержимое (контент) элемента последовательности'),
        ),
    ]
