# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0013_auto_20170504_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparisonquestion',
            old_name='question_content',
            new_name='comparison_question_content',
        ),
        migrations.RenameField(
            model_name='sequencequestion',
            old_name='question_content',
            new_name='sequence_question_content',
        ),
    ]
