# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0014_auto_20170504_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoftest',
            name='type_of_question',
            field=models.CharField(choices=[('ClsdQ', 'закрытый'), ('OpndQ', 'открытый'), ('SqncQ', 'последовательность'), ('CmprsnQ', 'сопоставление')], max_length=7, verbose_name='Тип теста, чтобы знать, к какому типу вопроса обращаться через связь'),
        ),
    ]
