# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0016_auto_20170418_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='tags',
            field=models.ManyToManyField(blank=True, to='octapp.Tag', verbose_name='Тег или теги теста'),
        ),
    ]
