# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0016_auto_20170504_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='openquestion',
            name='blank_width',
            field=models.IntegerField(default=50, verbose_name='Ширина пропуска в пикселях'),
        ),
    ]
