# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0017_openquestion_blank_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedquestion',
            name='only_one_right',
            field=models.BooleanField(default=True, verbose_name='Только один вариант ответа — правильный.'),
        ),
    ]
