# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0017_auto_20170419_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Наименование тега'),
        ),
    ]
