# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0018_auto_20170504_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedquestion',
            name='correct_option_numbers',
            field=models.CharField(help_text='Номера одного или нескольких правильных вариантов через запятую и без пробелов', max_length=55, verbose_name='Правильны(й/е) вариант/варианты'),
        ),
    ]
