# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0018_auto_20170419_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='anonymous_loader',
            field=models.BooleanField(default=False, verbose_name='Анонимный тест. На странице теста не будет указан пользователь, который загрузил тест.'),
        ),
    ]
