# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0019_test_anonymous_loader'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='ready_for_passing',
            field=models.BooleanField(default=False, editable=False, verbose_name='Готовность теста для прохождения другими пользователями'),
        ),
    ]
