# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 14:18
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0020_remove_openquestion_blank_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openquestion',
            name='question_content_after_blank',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Используйте сервисы хранения изображений, если требуется добавить картинку.', null=True, verbose_name='Содержимое (контент) после пропуска (может отсутствовать)'),
        ),
    ]
