# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 06:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('octapp', '0020_test_ready_for_passing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(verbose_name='Тест понравился? Если True — +1 к рейтингу, иначе — -1 к рейтингу')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, к которому относится данная пользовательская оценка (рейтинг)')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='octapp.Test', verbose_name='Тест, к которому относится данная пользовательская оценка (рейтинг)')),
            ],
        ),
    ]
