# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0021_test_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test_rate',
            options={'verbose_name': 'Оценка тестов', 'verbose_name_plural': 'Оценки тестов'},
        ),
    ]
