# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0021_auto_20170506_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openquestion',
            name='question_content_after_blank',
            field=models.TextField(blank=True, default='', help_text='Используйте сервисы хранения изображений, если требуется добавить картинку.', null=True, verbose_name='Содержимое (контент) после пропуска (может отсутствовать)'),
        ),
        migrations.AlterField(
            model_name='openquestion',
            name='question_content_before_blank',
            field=models.TextField(default='Заполните пропуск: ', help_text='Используйте сервисы хранения изображений, если требуется добавить картинку.', verbose_name='Содержимое (контент) перед пропуском'),
        ),
    ]
