# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0022_auto_20170506_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openquestion',
            name='question_content_before_blank',
            field=models.TextField(default='Заполните пропуск: \r\n', help_text='Используйте сервисы хранения изображений, если требуется добавить картинку.', verbose_name='Содержимое (контент) перед пропуском'),
        ),
    ]
