# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0022_auto_20170420_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_restricting',
            field=models.DateTimeField(null=True, verbose_name='Ограничение времени прохождения теста'),
        ),
    ]
