# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0026_auto_20170506_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedquestionoption',
            name='option_number',
            field=models.IntegerField(blank=True, help_text='Оставьте это поле пустым, чтобы добавить вариант вопроса последним (т.е. номер = кол-во вопросов + 1)', verbose_name='Порядковый номер варианта ответа на вопрос закр. типа'),
        ),
        migrations.AlterField(
            model_name='comparisonquestionelement',
            name='element_index_number',
            field=models.IntegerField(blank=True, help_text='Оставьте это поле пустым, чтобы добавить элемент ряда последним (т.е. номер = кол-во элементов + 1)', verbose_name='Порядковый номер элемента сопоставления'),
        ),
        migrations.AlterField(
            model_name='sequencequestionelement',
            name='element_index_number',
            field=models.IntegerField(blank=True, help_text='Оставьте это поле пустым, чтобы добавить элемент последним (т.е. номер = кол-во элементов + 1)', verbose_name='Порядковый номер элемента последовательности'),
        ),
    ]
