# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0028_auto_20170507_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openquestion',
            name='question_content_before_blank',
            field=models.TextField(default='Заполните пропуск: ', verbose_name='Содержимое (контент) перед пропуском'),
        ),
    ]
