# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0028_auto_20170421_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Наименование теста'),
        ),
    ]
