# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0029_auto_20170421_0104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'permissions': (('confirm_category', 'Can confirm_category'),), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_date'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='resultscale',
            options={'ordering': ['name'], 'verbose_name': 'Оценочная шкала', 'verbose_name_plural': 'Оценочные шкалы'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['name'], 'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
    ]
