# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 13:44
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0030_auto_20170421_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержимое комментария'),
        ),
    ]
