# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 13:50
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0031_auto_20170421_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Содержимое комментария'),
        ),
    ]
