# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0032_auto_20170421_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tests', to='octapp.Tag', verbose_name='Тег или теги теста'),
        ),
    ]
