# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0032_auto_20170508_0648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closedquestionoption',
            options={'ordering': ['question', 'option_number'], 'verbose_name': 'Вариант ответа на вопрос закрытого типа', 'verbose_name_plural': 'Варианты ответа на вопрос закрытого типа'},
        ),
        migrations.AlterModelOptions(
            name='comparisonquestionelement',
            options={'ordering': ['question', 'element_index_number'], 'verbose_name': 'Элемент левого или правого ряда в вопросе на сопоставление', 'verbose_name_plural': 'Элементы левого или правого ряда в вопросе на сопоставление'},
        ),
        migrations.AlterModelOptions(
            name='sequencequestionelement',
            options={'ordering': ['question', 'element_index_number'], 'verbose_name': 'Элемент для вопроса на определение последовательности', 'verbose_name_plural': 'Элементы для вопроса на определение последовательности'},
        ),
    ]
