# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 23:24
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0033_auto_20170508_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedquestion',
            name='correct_option_numbers',
            field=models.CharField(help_text='Номера одного или нескольких правильных вариантов через запятую.', max_length=55, verbose_name='Правильны(й/е) вариант/варианты'),
        ),
        migrations.AlterField(
            model_name='closedquestionoption',
            name='content',
            field=ckeditor.fields.RichTextField(default='', help_text='Используйте сервисы хранения изображений, если требуется добавить картинку. Не вводите пустые параграфы в качестве вариантов/элементов — такие варианты/элементы не будут добавлены. Также не будут добавлены варианты/последовательности, содержащие только пробелы.', verbose_name='Содержимое (контент) варианта ответа'),
        ),
        migrations.AlterField(
            model_name='comparisonquestion',
            name='correct_sequence',
            field=models.CharField(help_text='Перечислите здесь через запятую все правильные пары, например: 1-2, 2-1, 3-4, 4-3.', max_length=55, verbose_name='Правильные пары элементов левого и правого столбцов (рядов) сопоставления'),
        ),
        migrations.AlterField(
            model_name='comparisonquestionelement',
            name='element_content',
            field=ckeditor.fields.RichTextField(default='', help_text='Используйте сервисы хранения изображений, если требуется добавить картинку. Не вводите пустые параграфы в качестве вариантов/элементов — такие варианты/элементы не будут добавлены. Также не будут добавлены варианты/последовательности, содержащие только пробелы.', verbose_name='Содержимое (контент) элемента сопоставления'),
        ),
        migrations.AlterField(
            model_name='sequencequestion',
            name='correct_sequence',
            field=models.CharField(help_text='Номера элементов последовательности, разделенные запятыми, например 2, 3, 1, 4.', max_length=70, verbose_name='Правильная последовательность'),
        ),
        migrations.AlterField(
            model_name='sequencequestionelement',
            name='element_content',
            field=ckeditor.fields.RichTextField(default='', help_text='Используйте сервисы хранения изображений, если требуется добавить картинку. Не вводите пустые параграфы в качестве вариантов/элементов — такие варианты/элементы не будут добавлены. Также не будут добавлены варианты/последовательности, содержащие только пробелы.', verbose_name='Содержимое (контент) элемента последовательности'),
        ),
    ]
