# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0033_auto_20170422_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='Наименование категории'),
        ),
    ]
