# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0038_auto_20170517_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='only_registered_can_pass',
            field=models.BooleanField(default=False, verbose_name='Только зарегистрированные и авторизованные пользователи могут проходить тест'),
        ),
    ]
