# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapp', '0039_test_only_registered_can_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='fail_reason',
            field=models.CharField(blank=True, choices=[('выход курсора', 'выход курсора'), ('нажатие alt или ctrl', 'нажатие alt или ctrl')], max_length=27, null=True, verbose_name='Причина провала теста, если таковой имел место быть'),
        ),
    ]
